### PR TITLE
Fixes issues hitting breakpoints multiple times. Fixes #491.

### LINKED ISSUE #491: Same breakpoint hit multiple times
Repro code:
Python 2.7, set breakpoint on `print`. It can hit multiple times. This seems like a issue with breakpoint on first line.
```python
print('Hello')
```

Traceback from first hit:
```
  File "c:\users\kanadig\appdata\local\microsoft\visualstudio\15.0_8875dd93exp\extensions\microsoft corporation\python\15.8.0\ptvsd_launcher.py", line 119, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, run_as)
  File "C:\GIT\ptvsd\ptvsd\debugger.py", line 37, in debug
    run(address, filename, *args, **kwargs)
  File "C:\GIT\ptvsd\ptvsd\_local.py", line 48, in run_file
    run(argv, addr, **kwargs)
  File "C:\GIT\ptvsd\ptvsd\_local.py", line 99, in _run
    _pydevd.main()
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1719, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1073, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1080, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\kanadig\source\repos\PyScratch\PyScratch\Scratch3.py", line 1, in <module>
    print('hello')
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_trace_dispatch_regular.py", line 117, in trace_dispatch
    return thread_tracer.__call__(frame, event, arg)
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_trace_dispatch_regular.py", line 305, in __call__
    ).trace_dispatch(frame, event, arg)
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 644, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 134, in do_wait_suspend
    traceback.print_stack()
```

Traceback from second hit:
```
  File "c:\users\kanadig\appdata\local\microsoft\visualstudio\15.0_8875dd93exp\extensions\microsoft corporation\python\15.8.0\ptvsd_launcher.py", line 119, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, run_as)
  File "C:\GIT\ptvsd\ptvsd\debugger.py", line 37, in debug
    run(address, filename, *args, **kwargs)
  File "C:\GIT\ptvsd\ptvsd\_local.py", line 48, in run_file
    run(argv, addr, **kwargs)
  File "C:\GIT\ptvsd\ptvsd\_local.py", line 99, in _run
    _pydevd.main()
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1719, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1073, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1080, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\kanadig\source\repos\PyScratch\PyScratch\Scratch3.py", line 1, in <module>
    print('hello')
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 644, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 134, in do_wait_suspend
    traceback.print_stack()
```

### PR DESCRIPTION
**Pull request by fabioz**
Note: also brought some other changes:
- don't list threads marked as pydevd daemon threads
- fix issue hitting lamdas

### CODE REVIEW

**Comment by karthiknadig** [comment]
Will merge EOD if no other comments.

**Comment by karthiknadig** [comment]
Just noticed that this PR has a `pydevd` version change. @zooba We will need a code scan.

**Comment by fabioz** [comment]
Is this needed even if all the changes done there were done by myself under my contract with MS? (I raised the version because I'm keeping both in sync and I plan on doing a pydevd release soon).

**Comment by karthiknadig** [comment]
Would it be possible to split the bug fix into a separate PR. @zooba knows more about the code scanning requirement.

**Comment by fabioz** [comment]
Ok, I'll create 2 separate requests (one for this fix and another for the version update).

**Pull request closed without merging**
