### PR TITLE
Refactor before fixing support for re-attach.

### PR DESCRIPTION
**Pull request by ericsnowcurrently**
An alternative approach to fixing re-attach (in contrast to #287) requires separating some concerns that are currently mixed together in the code base.  This PR does so.

### CODE REVIEW

**Comment by int19h** [comment]
I really like this code reorganization, much neater! 👍

**Comment by DonJayamanne** [comment]
Got some issues, here's a screen dump of an error:
Basically running a program as follows fails:
`python -m ptvsd --server --port 9091 --file another.py`

screen shot 2018-04-02 at 9 32 45 pm

**Comment by DonJayamanne** [comment]
@ericsnowcurrently Please can we add tests for the above error (this is a regression issue). Right now unit tests are passing, but its breaking VSC, meaning we need some tests. I don't mind us creating a separate issue to track the creation of unit tests for this (i.e. we don't need the tests in this PR).

**Comment by DonJayamanne** [comment]
@ericsnowcurrently 
This PR breaks debugging using `launch` as well as `attach`.
Looks like we need some better unit tests. #292 is another example where we need unit tests for a similar if not exact scenaro.

screen shot 2018-04-02 at 9 32 45 pm
screen shot 2018-04-02 at 9 37 39 pm

**Comment by DonJayamanne** [comment]
> I really like this code reorganization, much neater compared to our existing everything-in-wrapper.py! 👍

Agreed.

**Comment by ericsnowcurrently** [comment]
@DonJayamanne This PR should no longer break debugging.  Please verify.  As to the tests, I agree and am working on it. :)

**Pull request merged**
