### PR TITLE
When a thread is created, notify about it as soon as possible.

### LINKED ISSUE #106: Delay between thread creation and thread created event is noticeably long
I added `print('Created [%d]: %s' % (tid, pyd_tid))` to `on_pydevd_thread_create` to demonstrate this issue. Each of the worker threads here wait for 1 second before printing.
```
Worker 0
Worker2 0
done
Worker 1
Worker 4
Worker 2
Worker 3
Worker2 3
Worker2 4
Worker2 2
Worker2 1
Worker 0
done
Worker2 0
Worker2 2
Worker2 4
Worker2 3
Worker 3
Worker 1
Worker 2
Worker 4
Worker2 1
done
Worker 0
Worker2 0
Worker2 1
Worker2 2
Worker2 4
Worker 3
Worker 4
Worker2 3
Worker 2
Worker 1
done
Worker 0
Worker2 1
Worker2 0
Worker2 2
Worker2 4
Worker 3
Worker 4
Worker 2
Worker2 3
Worker 1
Created [1]: pid_14012_id_1394645891840
Created [2]: pid_14012_id_1394662689928
Created [3]: pid_14012_id_1394662689816
Created [4]: pid_14012_id_1394662690208
Created [5]: pid_14012_id_1394662690432
Created [6]: pid_14012_id_1394662690656
Created [7]: pid_14012_id_1394662731960
Created [8]: pid_14012_id_1394662732240
Created [9]: pid_14012_id_1394662732520
Created [10]: pid_14012_id_1394662732800
Created [11]: pid_14012_id_1394662733080
```

### PR DESCRIPTION
**Pull request by fabioz**
Fixes #106.

### CODE REVIEW

**Comment by karthiknadig** [comment]
@fabioz: There seems to be an error that pops up specific to this change. See travis results for more info.
```
Traceback (most recent call last):
  File "/home/travis/build/Microsoft/ptvsd/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 594, in __call__
    global_debugger.notify_thread_created(thread_id, t)
  File "/home/travis/build/Microsoft/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 479, in notify_thread_created
    self.writer.add_command(self.cmd_factory.make_thread_created_message(thread))
AttributeError: 'NoneType' object has no attribute 'add_command'
```

**Comment by fabioz** [comment]
@karthiknadig already taking a look at it.

**Comment by fabioz** [comment]
@karthiknadig I still have to fix other tests failing (given that the thread notification changed the tests have to be updated).

**Comment by karthiknadig** [comment]
Looks good to me. Waiting for review from @ericsnowcurrently since there are changes to ptvsd internal threads.

**Comment by karthiknadig** [comment]
@ericsnowcurrently since you are familiar with this area, can you provide the info?

**Comment by fabioz** [comment]
Just updated the tests (I looked a bit more at the code and it seems I should add those statements before actually starting the code, so, it should be Ok now).

The tests should all be passing without any background errors (and the failure from VSTS is unrelated to any change in this pull request and travis is working).

**Comment by fabioz** [comment]
@karthiknadig please wait a bit more... I was doing some other tests here and it seems that with this patch it's possible to get into a deadlock when creating a thread if such a thread is created from inside of `process_internal_commands` (namely, if the user creates a thread during the evaluation of a command and waits for the thread to start running to proceed -- it's a corner case but should not break the debugger) -- this happens because the `_lock_running_thread_ids` is held for the whole `process_internal_commands`.

I'll provide an updated patch tomorrow.

**Comment by fabioz** [comment]
@karthiknadig ok, should be ready now. Had some issues because tests were flaky too (it seems the test was also failing on master -- hopefully my changes make it more consistent now).

**Pull request merged**
