### PR TITLE
[Blocked] Treat any code not in site-library as user code

### LINKED ISSUE #802: Just-my-code: Anything not in site-packages should be treated as user code

### PR DESCRIPTION
**Pull request by karthiknadig**
Fixes #802

Changing the approach for Just-my-code. In this PR we treat any code not in site-library as user code. 
@int19h Should we make this an option?

### CODE REVIEW

**Comment by int19h** [comment]
I think we'd want to enable the scenario where someone is authoring a library, and wants to debug it as it is after pip installs it locally. So an option for whether site-library is user code or not is a good one to have. 

Come to think of it, maybe instead of making it a flag, maybe we can reuse path mappings for this? i.e. for every entry there, allow the user to say that this folder is user code, regardless of any other setting.

**Comment by d3r3kk** [comment]
Special Derek VSTS power maneuver go!

**Comment by karthiknadig** [comment]
This is blocked by #854

**Comment by karthiknadig** [comment]
Will reopen this with the correct change.

**Pull request closed without merging**
