### PR TITLE
Fix for #620: Mix of unicode and str in filename conversion.

### PR DESCRIPTION
**Pull request by fabioz**

### CODE REVIEW

**Comment by karthiknadig** [comment]
Will merge this EOD if there are no other comments.

**Comment by DonJayamanne** [comment]
* What are we trying to fix here?
The issue isn't very clear.
@karthiknadig I thought we decided not to merge any PyDevD changes unless absolutely necessary? Right now I don't see how this meets that criteria?

**Comment by karthiknadig** [comment]
Ok. I will leave it open for now.

**Comment by fabioz** [comment]
@DonJayamanne @karthiknadig 

The actual error this fixes is in the screenshot below (I think it may also fail if the user has filenames with non ascii chars) -- I got this from a user directly from e-mail (note that this is only on Python 2).

error cython str unicode

**Comment by fabioz** [comment]
@DonJayamanne @karthiknadig just to complement, I introduced this bug in https://github.com/Microsoft/ptvsd/pull/533, and I think it's a critical fix for Python 2 (so, if https://github.com/Microsoft/ptvsd/pull/533 will be kept, it's critical that this is also applied).

**Pull request merged**
