### PR TITLE
Wait for handshake completion when waiting for attach.

### PR DESCRIPTION
**Pull request by ericsnowcurrently**
(see gh-448)

There is a race between attach and handshake completion that may result in breakpoints not being hit.  This PR fixes that by waiting for handshake completion when waiting for attach.

### CODE REVIEW

**Comment by ericsnowcurrently** [comment]
@DonJayamanne, I'll look at adding a test.

**Comment by karthiknadig** [comment]
This repros for me even with the change on Windows.

**Comment by ericsnowcurrently** [comment]
@karthiknadig, is that on VS?  The patch fixes the issue for me in VSC.

**Comment by ericsnowcurrently** [comment]
Unless there are any objections, I going to land this PR as-is.  (It does improve the situation.)  Then we can address the deficiency in `CMD_SET_BREAK` separately.

**Pull request merged**
