### PR TITLE
Remove code duplication in runner.py.

### PR DESCRIPTION
**Pull request by ericsnowcurrently**
(fixes gh-464)

The code in ptvsd/runner.py was originally copied from elsewhere and slightly adapted.  Over time the APIs diverged, which lead to the failure in gh-464.  This PR fixes the problem by getting rid of the code duplication.

### CODE REVIEW

**Comment by karthiknadig** [comment]
@DonJayamanne Can you take a look at this?

**Comment by DonJayamanne** [comment]
Failing with this error:
`
87 /Users/donjayamanne/Desktop/Development/PythonStuff/util/one.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/__main__.py", line 207, in <module>
    singlesession=args.single_session)
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/__main__.py", line 199, in main
    run_main(addr, name, kind, *extra, **kwargs)
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/_local.py", line 21, in run_main
    no_debug_runner(address, name, kind == 'module', *extra, **kwargs)
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/runner.py", line 26, in run
    if not daemon.wait_for_launch(address):
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/runner.py", line 108, in wait_for_launch
    notify_launch=launched.set,
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/daemon.py", line 197, in start_session
    self._check_ready_for_session()
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/daemon.py", line 243, in _check_ready_for_session
    raise DaemonStoppedError()
ptvsd.daemon.DaemonStoppedError: stopped
`

**Comment by ericsnowcurrently** [comment]
@DonJayamanne, would you mind taking another look?  Also, what is the "one.py" script that you ran (so I can try it locally)?

**Comment by DonJayamanne** [comment]
Tested with a simple print statement:
```python
print("Hello")
```

**Comment by ericsnowcurrently** [comment]
I've fixed the problem and verified that it works in VSC.

**Pull request merged**
