### PR TITLE
Fix #1875: Inject ptvsd into subprocesses

### LINKED ISSUE #1875: Inject ptvsd into subprocesses
The adapter should use the "evaluate" request to run `import ptvsd` (after setting up `sys.path`) in subprocesses when the debug server connects to it, so that user code can import the module later and do `ptvsd.break_into_debugger()` etc.

This also needs a test.

### PR DESCRIPTION
**Pull request by int19h**
Use "evaluate" request without "frameId" to import ptvsd into the debuggee as soon as server attaches.

Fix test_subprocess to use the new test API.

### CODE REVIEW

**Comment by int19h** [comment]
Do not merge - this breaks things at the moment due to some unclear issue with "evaluate".

**Comment by int19h** [comment]
@fabioz, can you take a look and verify whether I'm using "evaluate" correctly. For some reason, the "evaluate" request doesn't seem to be getting a response from pydevd in most scenarios, but not all. Since the injection is set up to happen even in single-proc, this can be trivially observed with `test_run` - attach-by-socket tests pass, but everything else fails. In pydevd logs, it looks like this:
```
Process EvaluateRequest: {
    "arguments": {
        "expression": "\nimport sys\nsys.path.insert(0, 'c:\\\\git\\\\ptvsd\\\\src')\ntry:\n    import ptvsd\nfinally:\n    del sys.path[0]\n",
        "format": {}
    },
    "command": "evaluate",
    "seq": 2,
    "type": "request"
}
```
and there's no response that follows, so the adapter just times out waiting for it.

I tried to trace the flow of the request inside of pydevd with prints. So far as I can see, it handles the request to the point where `internal_evaluate_expression_json` is posted to the command thread; but it never actually runs.

**Comment by fabioz** [comment]
I'll take a look.

**Comment by fabioz** [comment]
The issue is that in the 'settrace', pydevd does not start the auxiliary threads while it's not ready to run (so, it doesn't handle requests while it's not unblocked).

A fix for this would be starting those threads before doing that wait. I did the needed changes for that in  https://github.com/fabioz/ptvsd/commit/750f1bf16bdf867256c8f6ddd33bc91f6ac3cd26 (so, you can cherry-pick those changes in your branch).

**Comment by int19h** [comment]
@fabioz  Thanks! This solves the issue for `test_run`, but it appears to still be present for subprocesses. Same symptom - "evaluate" is received by pydevd, but no response is sent back, and there's nothing in the logs indicating any failure to process.

`test_subprocess` (any variant, e.g. `test_subprocess[program-launch]`), with changes in this PR, can be used to observe this. The test itself fails due to backchannel timeout, but that happens because the backchannel is being opened by the child process, and that code doesn't execute because the subprocess is not getting attached to.

**Comment by fabioz** [comment]
I'll investigate the issue.

**Comment by fabioz** [comment]
I started investigating the issue on Python 2.7 (where it seems that any launch with `runners.attach_by_socket["cli"]` deadlocks).

In this case the problem is the Python 2.7 import lock -- I'm posting the thread dump below, which I think is clear in showing why the deadlock happens.

```

-------------------------------------------------------------------------------
 Thread pydevd.CommandThread  (daemon: True, pydevd thread: True)

 File "C:\bin\Miniconda\envs\py27_tests\lib\threading.py", line 773, in __bootstrap
   self.__bootstrap_inner()
 File "C:\bin\Miniconda\envs\py27_tests\lib\threading.py", line 800, in __bootstrap_inner
   self.run()
 File "D:\x\ptvsd_workspace\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 156, in run
   self._on_run()
 File "D:\x\ptvsd_workspace\ptvsd\src\ptvsd\_vendored\pydevd\pydevd.py", line 175, in _on_run
   self.py_db.process_internal_commands()
 File "D:\x\ptvsd_workspace\ptvsd\src\ptvsd\_vendored\pydevd\pydevd.py", line 1468, in process_internal_commands
   int_cmd.do_it(self)
 File "D:\x\ptvsd_workspace\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 578, in do_it
   InternalThreadCommand.do_it(self, dbg)
 File "D:\x\ptvsd_workspace\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 547, in do_it
   self.method(dbg, *self.args, **self.kwargs)
 File "D:\x\ptvsd_workspace\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 1000, in internal_evaluate_expression_json
   dump_threads(stream=_LoggingGlobals._debug_stream)

# ... when about to evaluate "import ptvsd" it's never able to get the import lock.

-------------------------------------------------------------------------------
 Thread pydevd.Reader  (daemon: True, pydevd thread: True)
 
    -- nothing special here

-------------------------------------------------------------------------------
 Thread pydevd.Writer  (daemon: True, pydevd thread: True)

   -- nothing special here

-------------------------------------------------------------------------------
 Thread pydevd.CheckAliveThread  (daemon: False, pydevd thread: True)

  -- nothing special here

-------------------------------------------------------------------------------
 Thread MainThread  (daemon: False, pydevd thread: False)

 File "c:\Users\fabio\AppData\Local\Temp\pytest-of-fabio\pytest-451\test_step_multi_threads_progra0\code_to_debug.py", line 5, in <module>

   import debug_me  # noqa -- holding the import lock on Python 2.7 here!!!

   self: <Condition(<thread.lock object at 0x00000000039FDE30>, 1)>
 File "d:\x\ptvsd_workspace\ptvsd\tests\DEBUGGEE_PYTHONPATH\debug_me\__init__.py", line 44, in <module>
   eval(_code, {})
 File "<PTVSD_TEST_DEBUG_ME>", line 5, in <module>
 File "D:\x\ptvsd_workspace\ptvsd\src\ptvsd\__init__.py", line 47, in wait_for_attach
   return api.wait_for_attach()
 File "D:\x\ptvsd_workspace\ptvsd\src\ptvsd\server\api.py", line 35, in wait_for_attach
   pydevd._wait_for_attach(cancel=cancel_event)
 File "D:\x\ptvsd_workspace\ptvsd\src\ptvsd\_vendored\pydevd\pydevd.py", line 2424, in _wait_for_attach
   if py_db.block_until_configuration_done(0.1):
 File "D:\x\ptvsd_workspace\ptvsd\src\ptvsd\_vendored\pydevd\pydevd.py", line 656, in block_until_configuration_done
   return self._on_configuration_done_event.wait(timeout)
 File "C:\bin\Miniconda\envs\py27_tests\lib\threading.py", line 613, in wait
   self.__cond.wait(timeout)
 File "C:\bin\Miniconda\envs\py27_tests\lib\threading.py", line 358, in wait
   _sleep(delay)
```

**Comment by fabioz** [comment]
Ok, I did another change to support this use case -- you can cherry-pick it at: https://github.com/fabioz/ptvsd/commit/d34bde485812c54331fabb917672ae9520679ea2

I changed to process events in the thread that's currently waiting instead of starting threads as I did previously.

I also had to do a change to check if `ptvsd` was already loaded prior to the import to handle the case where the user does:

```
import ptvsd
ptvsd.enable_attach(...)
ptvsd.wait_for_attach()
```

In this case `ptvsd` will be already loaded and in `sys.modules`, and in that case the evaluation will be done in a thread (which would deadlock in the import statement) because we're no longer waiting for the initial configuration done.

**Comment by int19h** [comment]
Looks good, thanks!

**Pull request merged**
