### PR TITLE
Some pathutils fixes

### PR DESCRIPTION
**Pull request by karthiknadig**

### CODE REVIEW

**Comment by karthiknadig** [comment]
Highly likely VSTS failure is due to unstable tests. The mac OS tests passed [here](https://ptvsd.visualstudio.com/ptvsd/ptvsd%20Team/_build/results?buildId=273&view=logs) but failed [here](https://ptvsd.visualstudio.com/ptvsd/ptvsd%20Team/_build/results?buildId=275&view=logs), with the same PR.

**Comment by karthiknadig** [comment]
@DonJayamanne can you review this?

**Comment by DonJayamanne** [comment]
Wow, that's a lot of errors in CI. Please could you merge master to check. Currently we have fewer failing tests in the master branch.

**Comment by karthiknadig** [comment]
Merging this since it does not look like an issue with this change.

**Pull request merged**
