### PR TITLE
Clean up session handling in the daemon.

### LINKED ISSUE #459: Break on normal exit is not respected
Using Visual Studio
Enable Break on normal exit option

Result: Console does not wait for input at end of program

### PR DESCRIPTION
**Pull request by ericsnowcurrently**
This is part of the effort to fix gh-459.  While it doesn't fix it, it does clean up the Daemon code a little and resolves a potential issue with session lifecycle handling.  The solution for gh-459 will build on this.

### CODE REVIEW

**Comment by huguesv** [comment]
This didn't fix it for me :(

**Comment by ericsnowcurrently** [comment]
How does PTVS use ptvsd?  Does is call the ptvsd CLI?  If so, does it run it as a server or a client?

**Comment by huguesv** [comment]
From VS, we start up a process: `python.exe ptvsd_launcher.py <bunch of args>`, which calls into `ptvsd.debug()`
https://github.com/Microsoft/PTVS/blob/master/Python/Product/PythonTools/ptvsd_launcher.py#L111

**Comment by karthiknadig** [comment]
PTVS uses it as a client.

**Comment by ericsnowcurrently** [comment]
@huguesv Would you mind trying it again?

**Comment by karthiknadig** [comment]
Tried this. It is not fixed yet.

**Comment by ericsnowcurrently** [comment]
I'm going to merge this and then go from there.

**Comment by karthiknadig** [comment]
Ok, go ahead

**Pull request merged**
